### ISSUE TITLE
Missing SSL library prerequisite on the Ωhmcoin Project

### ISSUE THREAD

**Issue by gluneau** [theohmproject/ohmcoin#22]
#### Expected behavior

The `sudo ./configure` command should finish in a sucessful manner. 

#### Actual behavior

While building the karmanode of the Ωhmcoin Project on an instance of Ubuntu 18.04 I found a
Missing SSL library prerequisite because of the latest OpenSSL was incorrectly detected as LibreSSL. 

Running the `sudo ./configure` will cause this error to occur:
`configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!`

#### How to reproduce

The basic guide to install a karmanode can be found here:
* [Ωhmcoin Karmanode Setup Guide](https://www.ohmcoin.org/article.php?story=ohmcoin_karmanode_set_up_guide).

#### How to fix it

A similar issue was found [here](https://github.com/PIVX-Project/PIVX/issues/149)
The solutions is to install an older library.
`sudo apt-get install libssl1.0-dev`

I also found another missing prerequisite, although it just a warning: 
`configure: WARNING: libzmq version 4.x or greater not found, disabling`

Here is what to do:
`sudo apt install libzmq3-dev`

#### Machine specs:
- OS: Ubuntu 18.04
- RAM: 1G
- Disk Type (SDD):

**Comment by 2a5A1Ghu1** [comment]
Confirmed, I will update the tut shortly.

**Comment by 2a5A1Ghu1** [comment]
All fixed thank you for your help. Let me know your discord name and I will toss you some ohm is this falls under our standing bounty!!!

**Comment by gluneau** [comment]
My discord account is helo#3194
